analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.1054078228771687
  brandStrength: 0.7656642
  lightness: 0.765178503235802
  brandColors:
    - '#509EE8'
    - '#181C03'
    - '#3C4C1D'
    - '#60821D'
    - '#46637D'
  rhythmicContrast: 0.7116113272495568
typography_spectrum: 0.06203008
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.7155389
favicon: null
name: Andrea Francesco Berni
